set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if(DEFINED ENV{ECHO_SDK_ROOT})
    set(_RV1106_DEFAULT_SDK_ROOT "$ENV{ECHO_SDK_ROOT}")
else()
    set(_RV1106_DEFAULT_SDK_ROOT "/opt/rv1106-sdk")
endif()

set(RV1106_SDK_ROOT
    "${_RV1106_DEFAULT_SDK_ROOT}"
    CACHE PATH "RV1106 SDK root"
)
set(RV1106_TOOLCHAIN_ROOT
    "${RV1106_SDK_ROOT}/tools/linux/toolchain/arm-rockchip830-linux-uclibcgnueabihf"
)
set(RV1106_TOOL_PREFIX
    "${RV1106_TOOLCHAIN_ROOT}/bin/arm-rockchip830-linux-uclibcgnueabihf"
)

set(CMAKE_C_COMPILER
    "${RV1106_TOOL_PREFIX}-gcc"
    CACHE FILEPATH "RV1106 C compiler"
)
set(CMAKE_AR
    "${RV1106_TOOL_PREFIX}-ar"
    CACHE FILEPATH "RV1106 archiver"
)
set(CMAKE_RANLIB
    "${RV1106_TOOL_PREFIX}-ranlib"
    CACHE FILEPATH "RV1106 ranlib"
)

set(CMAKE_FIND_ROOT_PATH "${RV1106_TOOLCHAIN_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
